name: Linux CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false

        matrix:
            include:
            # --- Linux x64 ---
            - os: ubuntu-latest
              build_type: Debug
              compiler: { c: gcc, cpp: g++ }

            - os: ubuntu-latest
              build_type: Debug
              compiler: { c: clang, cpp: clang++ }

            # --- Linux ARM ---
            - os: ubuntu-24.04-arm
              build_type: Debug
              compiler: { c: gcc, cpp: g++ }

            - os: ubuntu-24.04-arm
              build_type: Debug
              compiler: { c: clang, cpp: clang++ }
        
    steps:
      # -----------------------------
      # Checkout repository
      # -----------------------------
      - name: Checkout code
        uses: actions/checkout@v6

    
      # -----------------------------
      # Install dependencies
      # -----------------------------
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            cmake \
            build-essential \
            libboost-dev

      # -----------------------------
      # Configure
      # -----------------------------
      - name: Configure CMake
        run: >
          cmake -S ${{ github.workspace }} -B build -G Ninja
          -DCMAKE_C_COMPILER=${{ matrix.compiler.c }}
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DBUILD_EXAMPLE=ON
          -DBUILD_TESTS=ON

      # -----------------------------
      # Build
      # -----------------------------
      - name: Build project
        run: |
          cmake --build build --config ${{ matrix.build_type }}

      # -----------------------------
      # Run tests
      # -----------------------------
      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure